[[variable]]
prompt = 'Application Name: '
name = 'name'

[[variable]]
prompt = 'Author: '
name = 'author'
value = 'Jimmie'

[[variable]]
prompt = 'First: '
name= 'first'

[[variable]]
prompt = 'Second: '
name = 'second'

[[variable]]
prompt = 'Third: '
name = 'third'