mod cache_subcommand;
mod config_subcommand;
mod actions_subcommand;
mod check_subcommand;
mod connect_subcommand;
mod eval_subcommand;
mod ide_subcommand;
mod interface_subcommand;
mod learn_subcommand;
mod mcp_subcommand;
mod search_subcommand;
mod server_subcommand;

pub use cache_subcommand::handle_cache_subcommand;
pub use actions_subcommand::handle_commands_subcommand;
pub use config_subcommand::handle_config_subcommand;
pub use check_subcommand::handle_check_subcommand;
pub use connect_subcommand::{resolve_client_options, resolve_endpoint};
pub use eval_subcommand::handle_eval_subcommand;
pub use ide_subcommand::{handle_ide_subcommand, Manage};
pub use interface_subcommand::handle_interface_subcommand;
pub use learn_subcommand::{handle_introspect_subcommand, handle_learn_subcommand, handle_skill_subcommand};
pub use mcp_subcommand::handle_mcp_subcommand;
pub use search_subcommand::handle_search_subcommand;
pub use server_subcommand::handle_server_subcommand;