[package]
name = "archetect"
version = "0.1.0"
authors = ["Jimmie Fulton <jimmie.fulton@gmail.com>"]
edition = "2018"

[[bin]]
name = "archetect"
path = "src/bin/main.rs"

[dependencies]
clap = "2.33"
pest = "2.1.1"
pest_derive = "2.1.0"
failure = "0.1.5"
read_input = "0.8"
serde = "1.0.90"
serde_derive = "1.0.90"
tera = { path = "../tera" } # "1.0.0-beta.4"
toml = "0.5"