[package]
name = "archetect"
version = "0.1.0"
authors = ["Jimmie Fulton <jimmie.fulton@gmail.com>"]
edition = "2018"

[[bin]]
name = "archetect"
path = "src/bin/main.rs"

[dependencies]
clap = "2.33"
error-chain = "0.12"
heck = "0.3.1"
pest = "2.1.1"
pest_derive = "2.1.0"
failure = "0.1.5"
memchr = { version = "2", default-features = false }
read_input = "0.8"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.40"
tempfile = "3.1.0"
tera = { git = "https://github.com/jimmiebfulton/tera", branch = "v1" }
toml = "0.5"