[workspace]
resolver = "2"

members = [
  "archetect-api",
  "archetect-cli",
  "archetect-core",
  # "archetect-models",
  "archetect-terminal-io",
  "vendor/minijinja",
  "vendor/inquire",
]

[workspace.dependencies]
assert_matches = "1.5.0"
serde = { version = "1.0.159", features = ["derive"] }
log = { version = "0.4", features = ["std"] }

