[package]
name = "archetect-api"
version = "2.0.0-ALPHA.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
