[package]
name = "archetect-cli"
version = "0.2.0"
authors = ["Jimmie Fulton <jimmie.fulton@gmail.com>"]
edition = "2018"
license = "MIT"

[[bin]]
name = "archetect"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
archetect = { path = "../archetect-lib" }
clap = "2"
indoc = "0.3"
lazy_static = "1.0"
linked-hash-map = { version = "0.5.2", features = ["serde_impl"] }
log = "0.4"
read_input = "0.8"
serde = "1.0.90"
toml = "0.5"
