[package]
name = "archetect-terminal-io"
version = "2.0.0-ALPHA.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
archetect-api = { path = "../archetect-api", version = "2.0.0-ALPHA.6" }
inquire = { path = "../vendor/inquire", version = "0.6.0" }

log = { workspace = true }
dyn-clone = "1"
