#!/usr/bin/env python3
"""
{{ project_name }} - Main application file
Generated by Archetect archive demo
"""

def main():
    print("Hello from {{ project_name }}!")
    print("This project demonstrates Archetect's archive functionality.")

if __name__ == "__main__":
    main()