name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Ubuntu
        run: sudo apt update -y

      - name: Install Protoc
        run: sudo apt install -y protobuf-compiler

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test
